# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, any::devtools, any::rmarkdown, local::.
          needs: website

      - name: Install TinyTeX
        shell: Rscript {0}
        run: |
          if (!requireNamespace("tinytex", quietly = TRUE)) install.packages("tinytex")
          if (!tinytex::is_tinytex()) tinytex::install_tinytex()

      - name: Build vignettes
        shell: Rscript {0}
        run: |
          devtools::build_vignettes()

      - name: Build site
        shell: Rscript {0}
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

      - name: Copy PDF vignettes to docs/
        run: |
          mkdir -p docs
          cp inst/doc/*.pdf docs/ || true


      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: true
          branch: gh-pages
          folder: docs
