- name: Test coverage
  run: |
    cov <- covr::package_coverage(
      quiet = FALSE,
      clean = FALSE,
      install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
    )
    print(cov)
    covr::to_cobertura(cov, file = "cobertura.xml")  # ✅ Save file
  shell: Rscript {0}

- uses: codecov/codecov-action@v5
  with:
    files: ./cobertura.xml
    fail_ci_if_error: true
    # token: ${{ secrets.CODECOV_TOKEN }}  # For private repos only
